/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author xXEpickXx
 */
public class usuario extends javax.swing.JFrame {

    /**
     * Creates new form usuario
     */
    public usuaio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Nombre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setBackground(new java.awt.Color(153, 153, 153));
        Nombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        Nombre.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 37, -1, -1));

        jLabel2.setText("Apellido");
        Nombre.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 75, -1, -1));

        jLabel3.setText("Edad");
        Nombre.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 108, -1, -1));

        jLabel4.setText("Sexo");
        Nombre.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 146, -1, -1));

        jLabel5.setText("Numero");
        Nombre.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 184, -1, -1));

        jLabel6.setText("Dirección");
        Nombre.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 222, -1, -1));
        Nombre.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 34, 60, -1));
        Nombre.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 72, 60, -1));
        Nombre.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 105, 60, -1));
        Nombre.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 143, 60, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        Nombre.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 181, 60, -1));
        Nombre.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 219, 60, -1));

        jLabel7.setText("Usuario");
        Nombre.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 260, -1, -1));

        jLabel8.setText("Contraseña");
        Nombre.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 302, -1, -1));
        Nombre.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 257, 60, -1));
        Nombre.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 299, 60, -1));

        jLabel9.setText("Roll");
        Nombre.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 340, 39, -1));
        Nombre.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 60, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        Nombre.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 400, 370));

        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
